name: type-rig
version: 0.1
author: "Ashley Yakeley"
copyright: "(c) 2022 Ashley Yakeley"
license: BSD-2-Clause
license-file: LICENSE
maintainer: "<ashley@semantic.org>"
github: "AshleyYakeley/type-rig"
synopsis: Classes for the rig (sums and products) of types
category: Data
build-type: Simple

extra-source-files:
  - ChangeLog.md

default-extensions:
  - AllowAmbiguousTypes
  - Arrows
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - EmptyCase
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - ForeignFunctionInterface
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - ImplicitParams
  - NoImplicitPrelude
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - OverloadedLabels
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PatternSynonyms
  - PolyKinds
  - QuantifiedConstraints
  - RankNTypes
  - RecordWildCards
  - RecursiveDo
  - RoleAnnotations
  - ScopedTypeVariables
  - StandaloneDeriving
  - StandaloneKindSignatures
  - NoStarIsType
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeInType
  - TypeOperators
  - TypeSynonymInstances
  - UndecidableInstances
  - UndecidableSuperClasses
  - ViewPatterns
ghc-options:
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wcompat
  - -Wnoncanonical-monad-instances
  - -Wno-partial-type-signatures

library:
  source-dirs: lib
  dependencies:
    - base >= 4.15 && < 5
    - invariant >= 0.6
  exposed-modules:
    - Data.TypeRig.Summish
    - Data.TypeRig.Productish
    - Data.TypeRig.Riggish
    - Data.TypeRig
  other-modules: []
