name:                type-rig
version:             0.1.0.0
github:              "AshleyYakeley/type-rig"
license: BSD-2-Clause
license-file: LICENSE
author:              "Ashley Yakeley"
maintainer:          "ashley@semantic.org"
copyright:           "2022 Ashley Yakeley"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/AshleyYakeley/type-rig#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: lib
